### ISSUE TITLE
Add `building=riding_hall` as new type

### ISSUE THREAD

**Issue by simonschaufi** [openstreetmap/id-tagging-schema#1012]
### OSM Tag(s)

building=riding_hall

### How would you like this tag to see supported?

As a Preset

### Label

Riding hall

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:building=riding_hall

### Status of the Tag

In use

### Usage of the tag

1.749

### Further Information

Currently, `building=riding_hall` can only be entered manually in the tags, but not selected via the search. It would be more convenient if it would be available. I've also seen this issue https://github.com/openstreetmap/id-tagging-schema/issues/273 and I'm not sure if i request the opposite of it or not.

**Comment by Hufkratzer** [comment]
> I've also seen this issue #273 and I'm not sure if i request the opposite of it or not.

I think it's not the opposite and it would be helpful to have such a preset. Mainly because I have often observed that mappers, especially newbies, who want to indicate that an already mapped building is a riding hall, use the preset for [horse_riding](https://wiki.openstreetmap.org/wiki/Tag%3Aleisure%3Dhorse_riding), which is not intended for a building, but for the entire area of an equestrian facility. And when they do, iD removes the building tag from that object and the building is no longer rendered as a building. A preset for riding_hall could hopefully reduce these cases.

Some further remarks: 
- AFAIK, in English riding halls are more frequently called "indoor arenas" (see [wikipedia discussion](https://en.wikipedia.org/wiki/Talk:Riding_hall#Arena)), so the label/name should contain that, perhaps "Horseback Riding Indoor Arena / Riding Hall" of "Indoor Horseback Riding Arena / Riding Hall" (too long?).
- The status of the tag is not `Approved` but `In use`

**Comment by simonschaufi** [comment]
I've changed the status.
In German it's called Reithalle and the whole area a Reiterhof.
