### ISSUE TITLE
Deprecate `crossing_ref=zebra` to `crossing:markings=zebra`(?)

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#1119]
### Deprecated OSM Tag(s)

`crossing_ref=zebra`

### Replacement OSM Tag(s)

`crossing:markings=zebra`

### Link to OSM Wiki page

It looks like there is no official deprecation documented.

### Further Information

_Disclaimer:_ This is more of a question than a statement / proposal. I am not following the discoure on this topic closely enough. **I hope that we can share our views on the current state of the community consensus** in preparation of [a possible crossing refactoring](https://github.com/openstreetmap/id-tagging-schema/pull/1044#issuecomment-1948014249).

---

The id-tagging-schema does have no mention of `crossing_ref`, `crossing_ref=zebra` ATM. However, the tag is still widely used. However, it has 1.000.000 usage (https://taginfo.openstreetmap.org/tags/crossing_ref%3Dzebra#map)

The wiki https://wiki.openstreetmap.org/wiki/Tag:crossing_ref%3Dzebra does not mention any deprecation ATM. The german version https://wiki.openstreetmap.org/wiki/DE:Key:crossing#Weitere_gebr%C3%A4uchliche_Werte does not recommend anything clearly but mentions everything. The general https://wiki.openstreetmap.org/wiki/Key:crossing_ref page marked as controversial in general. The German version leaves the decision open, again https://wiki.openstreetmap.org/wiki/DE:Key:crossing_ref.

In terms of numbers: 600k `crossing:markings=zebra`, 1.100k `crossing_ref=zebra`
https://taghistory.raifer.tech/?#***/crossing_ref/zebra&***/crossing%3Amarkings/zebra
(Which does not factor in double tagging.)

(It looks like https://wiki.openstreetmap.org/wiki/Crossings#Street_crossings suggests the new tagging as a replacement.)

---

What is your take on deprecations? Is the discourse at a place where a deprecation would be possible?

Or should the id-tagging-schema instead have a unsearchable copy of the `crossing:markings=zebra` version until the numbers changes enough?

**Comment by tordans** [comment]
Ping @1ec5 because you talked about the topic in https://github.com/openstreetmap/id-tagging-schema/issues/408 .

**Comment by 1ec5** [comment]
As I understand it, `crossing:markings=zebra` is named after `crossing=zebra` and `crossing_ref=zebra`, but it isn’t necessarily being used to mean the same thing as `crossing_ref=zebra` in every region. Since `crossing_ref=*` is primarily intended to refer to a comprehensive configuration, some mappers have taken it to also imply other things like signage. I would tread more carefully with this tag than with `crossing=zebra`.

**Comment by tordans** [comment]
@1ec5 how to you think this repo should handle the tag? As it does not handelte it at all ATM.

**Comment by 1ec5** [comment]
Since `crossing_ref` is defined to vary by region, much like `designation`, I’m not sure a global rule or preset field would be very useful. But maybe a country-specific preset could set `crossing_ref` if desired.

**Comment by osmuser63783** [comment]
Because the meaning of `crossing_ref` is country-specific, I think country-specific presets make sense.

I suggested this in the UK community [here](https://community.openstreetmap.org/t/zebra-crossing-deprecation-proposal/115300/23) and [here](https://community.openstreetmap.org/t/uk-quarterly-project-2024-q4-pedestrian-crossings/119792/8) and so far the response has been positive. But I haven't had time to work on a PR yet.

**Comment by k-yle** [comment]
See also: #1403

I'm sure this has been discussed extensively, but just adding this info to the github issue:  Changing `crossing_ref=zebra` to `crossing:markings=zebra` would be wrong in AU & NZ,

because a "zebra crossing" is not the same thing as `crossing:markings=zebra`:
- There are zebra crossings which are not painted as zebra stripes
- There are crossings painted with zebra stripes which are not "zebra crossings"

**Comment by tordans** [comment]
AFAIK we don't have the ability to make deprecations country specific, so I think this it's save to close this issue for the foreseeable future.
