### ISSUE TITLE
Needleleaved deciduous trees and broadleaved evergreen trees - provide entries covering them or drop leaf lifecycle from current ones

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#1156]
Current entries make more likely that someone will tag this rarer trees badly.

![screen](https://github.com/openstreetmap/id-tagging-schema/assets/899988/367aa299-01e2-4eb1-9b2f-749f115a7a26)
![screen01](https://github.com/openstreetmap/id-tagging-schema/assets/899988/1f554189-b4bd-42f1-881c-bfb30d972f5b)

**Comment by tyrasd** [comment]
These presets do already exist, but are currently not searchable. See https://github.com/openstreetmap/id-tagging-schema/pull/956#issuecomment-1638817711

I don't remember the full details behind the decision back then, but we were probably just overly cautious to not provide too many specialized presets when searching for "Tree"… but it's probably fine to extend the search results to offer the 5 most common cases instead of only the 3 most common ones.

> more likely that someone will tag this rarer trees badly

Have you seen the mistake being made more often since the presets were added?

**Comment by matkoniecz** [comment]
> Have you seen the mistake being made more often since the presets were added?

I have not analysed the data but I almost made this mistake myself.

> Actually, the combination of leaf_type=broadleaved and leaf_cycle=evergreen is actually quite a bit more [common in OSM](https://taginfo.openstreetmap.org/tags/leaf_type=broadleaved#combinations) than what I would have initially guessed…

I think these type of trees are more popular in warmer parts of the world without serious winters
