### ISSUE TITLE
Is there a way to remove `playground:theme=playground` from the suggestion list?

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#1188]
**Describe the bug**

I monitor new user activity and I see quite a few playgrounds with `playground:theme=playground`.
Example: https://osmcha.org/changesets/149253152?aoi=4da8bade-add6-49e0-b2d6-9baf69253667

I expect users to just fill in what makes most sense from the list in iD. However, this value is given by Taginfo (I assume…) and should not be used.

Is there a way to remove it from the auto suggestion list … without taking over the whole list as a fixed list?

**Comment by 1ec5** [comment]
In the past, we’ve had some other malformed values crop up due to an import, such as `country=Tanzania` in https://github.com/openstreetmap/iD/issues/7123#issuecomment-653817884, which we simply fixed in the database. However, this appears to be organic usage. `playground:theme=playground` has the [straightest hockey stick graph](https://taginfo.openstreetmap.org/tags/playground:theme=playground#chronology) I’ve ever seen on taginfo, and it’s somewhat broadly distributed geographically.

There are some other tautological key-value pairs, such as `traffic_signals=signals`, but they sort of get a pass as an affirmation that no other value applies (so an editor like StreetComplete wouldn’t need to bother asking). For something more freeform like `playground:theme`, a tautological value is probably less useful.

**Comment by tordans** [comment]
Maybe we should just demote the theme tag from the `leisure=playground` preset into a "moreTags".
It is super prominent right now https://ideditor.netlify.app/#background=Berlin-2018&disable_features=boundaries&id=w60443941&map=20.00/52.47433/13.44798 and it really should not be…

<img width="406" alt="image" src="https://github.com/openstreetmap/id-tagging-schema/assets/111561/172a3124-b796-4e4a-ae35-17baf8753903">

**Comment by tordans** [comment]
> Maybe we should just demote the theme tag from the `leisure=playground` preset into a "moreTags".

I did just that in https://github.com/openstreetmap/id-tagging-schema/pull/1191

**Comment by matkoniecz** [comment]
> However, this appears to be organic usage. 

It seems to me to be induced by iD interface (prominence of field, high position on unmoderated list) and applied without some deeper intention.

I would consider removing it from database. Maybe ask some sample of people adding it?

**Comment by 1ec5** [comment]
> It seems to me to be induced by iD interface (prominence of field, high position on unmoderated list) and applied without some deeper intention.

Maybe, I just meant that it doesn’t look like an import. It clearly grew thanks to prominent placement in iD, but normally that effect is less stark than what we see here. It’s almost as if there was a campaign to set the field, now that it’s available in iD.

**Comment by matkoniecz** [comment]
I would not really call it organic. I expect that people setting it have no idea what they are actually doing and if such prominent location would disappear the growth would stop.

**Comment by tyrasd** [comment]
The field was now moved to the optional fields. 

There is however one more thing we could do: iD will not autosuggest tag values which are in the `deprecated.json` list. It is possible to add a tag to that list even without a `replace`ment tag. For these tag, iD will also show the "tag issue" warning and suggest to simply remove the tag. Currently, this is already used for the tags `content=unkown` (a field of the storage tank preset) and `operator:type=unknown`.

As the tag `playground:theme=playground` seems to add little to no information, so maybe it should also be added to the "deprecated" tags list?

**Comment by tordans** [comment]
I think a deprecation is a good idea!

**Comment by tyrasd** [comment]
done in ed497a32
