### ISSUE TITLE
iD warning recommends incorrectly mapping traffic_calming=table on a highway=way as a closed area

### ISSUE THREAD

**Issue by rskedgell** [openstreetmap/id-tagging-schema#1279]
**Describe the bug**
iD warning recommends incorrectly mapping traffic_calming=table on a highway=* way as a closed area.

**To Reproduce**
Warning appeared while editing tags on https://www.openstreetmap.org/way/844656505 and adjacent ways.

**Expected behavior**
iD should follow the wiki, which for [traffic_calming=table](https://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Dtable) states that the tag should be used on nodes and ways, but not areas or relations. If iD contributors wish to redefine a tag, please go through the normal proposal process like everyone else.

**Comment by tordans** [comment]
Can someone help figuring out what the system is doing here?

[This is the way in iD](https://www.openstreetmap.org/edit?way=844656505#map=19/51.57664/-0.03554)

My take is, that since since the [highway service preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/highway/service.json) does not a traffic calming field, it has to be the [traffic calming table preset](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/traffic_calming/table.json) which is also triggered by the tag on the highway?
Is this something the system does, triggering multiple presets on one object, only show the fields and such of the top one but add warnings of the secondary preset?

Another weird thing is, that the German wording for the preset `hw=service` "Zufahrtsweg" is not used in the yellow issue where the term "Betriebs-/Rangierfläche" is used. This might be a separate issue, though.
<img width="380" alt="image" src="https://github.com/openstreetmap/id-tagging-schema/assets/111561/8a4b2387-e67a-4387-8d09-6ef9489380fa">

I now see https://github.com/openstreetmap/id-tagging-schema/pull/1076 which sounds like the same issue. Could it be that this was released in https://github.com/openstreetmap/id-tagging-schema/blob/main/CHANGELOG.md#670 so this has to be something new. Maybe @ireun can help?

**Comment by 1ec5** [comment]
This is a duplicate of #1175.

**Comment by rskedgell** [comment]
> This is a duplicate of #1175.

So it is. We've had iD telling people to break correctly tagged traffic calming measures for over 3 months without a fix?! Oh, joy.
