### ISSUE TITLE
sloped_curb=yes - is it really safe to assume kerb=lowered?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#128]
See https://github.com/openstreetmap/id-tagging-schema/blob/main/data/deprecated.json#L1451

Note that at least some values of `sloped_curb` are mapping to rather `flush`.

Is it safe to assume that `sloped_curb=yes` means `kerb=lowered` rather than for example `flush`?

**Comment by quincylvania** [comment]
I don't know how people applied this tag in every circumstance, but it felt safe to assume "sloped" means there's a slope involved and therefore these aren't flush by default. People added a few values like `sloped_curb=at_grade` that would seem to indicate `kerb=flush`, and iD [accounts for them](https://github.com/openstreetmap/id-tagging-schema/blob/9fdecc983443ce75185c2923caae9f7703f2cae4/data/deprecated.json#L1411-L1453).

Since `lowered` and `flush` are both assumed to be wheelchair-accessible, and since wheelchair access is the main point of tagging these, and since updating these manually would require thousands of on-the-ground surveys, I'm confident in leaving the existing behavior even if it's not 100% accurate.
