### ISSUE TITLE
further clarification of guidelines re "useful purpose"

### ISSUE THREAD

**Issue by jnicho02** [openstreetmap/id-tagging-schema#1316]
I like the improvements to https://github.com/openstreetmap/id-tagging-schema/blob/main/GUIDELINES.md but take minor issue with the definition of "useful purpose".

> Useful Purpose: OSM allows for the collection of a wide variety of data, but not all of it is useful. For example, the brightness of street lamps might be documented, but it doesn't necessarily warrant a preset or field.

Niche data _is_ useful to somebody, just not to the wider body of users. For example, users of a [notional] personal safety app identifying well lit safe routes home may find brightness of street lamps very useful. However, one app probably doesn't warrant an iD preset.

I propose:

> Notable Purpose: OSM allows for the collection of a wide variety of data, *some of it for niche or non-obvious purposes*. For example, the brightness of street lamps might be documented, but it doesn't necessarily warrant a preset or field.

I know that i'm being pedantic, but OSM is a wide church and all [data] are welcome, just not necessarily welcome to a preset

**Comment by tordans** [comment]
@jnicho02 thanks for raising this! I agree that this can be worded better. How about https://github.com/openstreetmap/id-tagging-schema/pull/1318/files ?

I took your text but without the "non-obvious" because IMO a non-obvious tag can still be included based on "should have a practical application".

What are your thoughts @jnicho02?

---

Reading it again, there are other nuances here that we could try to improve but I would rather improve this once we have a more concrete case like a PR that makes us question the guidelines. I find it easier to clarify these things based on a practical case.

**Comment by jnicho02** [comment]
Looks good to me.

**Comment by matkoniecz** [comment]
> @[tordans](https://github.com/tordans) tordans added the[ waitfor-pr ](https://github.com/openstreetmap/id-tagging-schema/labels/waitfor-pr)label [Sep 1, 2024](https://github.com/openstreetmap/id-tagging-schema/issues/1316#event-14094685855)

seems that https://github.com/openstreetmap/id-tagging-schema/pull/1318 exists already so it does not wait for PR

**Comment by tordans** [comment]
> seems that #1318 exists already so it does not wait for PR

I renamed the label to "waitfor-pr-merge". The label description already explained this, but this makes it more explicit…
