### ISSUE TITLE
Status of this repo

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/id-tagging-schema#137]
Hi @quincylvania 

I've long used the translated preset files https://github.com/openstreetmap/id-tagging-schema/tree/main/dist/translations to generate list of synonyms https://github.com/MarcusWolschon/osmeditor4android/tree/master/src/main/assets/synonyms 

Before I rejig my code to use this repository just a check for good form: can I assume that the layout and location of things are going to stay "reasonably" stable going forward?

**Comment by quincylvania** [comment]
> can I assume that the layout and location of things are going to stay "reasonably" stable going forward?

@simonpoole Yes, we have iD working with the current setup and I don't see any major changes on the horizon regarding the file structure. But since we're using semantic versioning now, you could be extra safe by targeting distributed files by major version like:

https://cdn.jsdelivr.net/npm/@openstreetmap/id-tagging-schema@3/dist/translations/de.min.json

**Comment by bryceco** [comment]
I'm interested in always tracking the latest version, but I want my code to assert when the major version changes. How do I detect that automatically? (NSI now has a _meta component I can check)
