### ISSUE TITLE
common error : departure_board -> departures_board

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/id-tagging-schema#143]
departure_board is a common mistake for departures_board
while waiting for the correction of all the elements in the database, how to avoid that iD proposes the wrong value when the user types the beginning of the key? i was thinking about an addition in https://github.com/openstreetmap/id-tagging-schema/blob/main/data/deprecated.json but it's not really a deprecated tag. is there another place for correction or filtering of common errors?
PS: if it's this file that needs to be modified, I'll take care of it.

**Comment by tyrasd** [comment]
We can't include every possible typo. This one does (currently) also not even look like a very common one: there are only 2 instances in OSM. Granted, it used to be more (around 120 or so) at the time when this ticket was opened, but I just checked a few of them and almost all of them were introduced using the JOSM editor.[^1]

I think this one just needs a proper preset :arrow_right: #102.

[^1]: which is of course not a coincidence, because JOSM's much larger focus on raw tag input.
