### ISSUE TITLE
Encourage adding operator's name on power supports in France

### ISSUE THREAD

**Issue by flacombe** [openstreetmap/id-tagging-schema#219]
Dear maintainers,

As required for a national project, we're currently assigning the appropriate operator=* on a great amount of power poles/towers on French distribution power grids.
https://www.openstreetmap.org/user/InfosReseaux/diary/396044

119 companies operate their part of this distribution grid and a lot of time is needed to catch up on existing features to complete them with appropriate value of operator=* depending on their location.
In the same time, other mappers add new poles on their own and forget about operator=* which require regular cleanups.

Is it possible to raise a warning in case of power=pole,tower located in France without operator=* on them please?
JOSM already has this quality check. It reduces a lot the amount of operator-unknown features and iD now remains the main editor encouraging this.

Best regards

**Comment by Adamant36** [comment]
> Is it possible to raise a warning in case of power=pole,tower located in France without operator=* on them please?

It would probably be bad to have a warning if there's no operator since it's technically not an error. As operator isn't a required tag for utility poles.

**Comment by flacombe** [comment]
Did you read the linked diary?

Such a tool won't take care of poles lacking operator value for instance.
https://enedis.openstreetmap.fr/
It's not possible to make a proper usage of data as we're not able to get the responsible operator for a given damaged pole (for instance)
JOSM already warns for lacking operator and data quality is improving quickly thanks to mappers seeking for this information

**Comment by Adamant36** [comment]
> Did you read the linked diary?

Yes, but so what? Any random person can write a diary entry and say whatever they want in it. That doesn't mean it's authoritative or that their suggestion should be automatically implemented without question though. 

> It's not possible to make a proper usage of data as we're not able to get the responsible operator for a given damaged pole (for instance)

I mean, it would be if you add the operator tag yourself after the pole is mapped right? It's pretty easy to do a OverPass Turbo search for poles that don't have the operator tag. It's not worth having a warning for something that's not wrong tagging just because you don't want to out the effort though. 

Otherwise, it's kind of a slippery slope. Should we have warnings for buildings without addresses? Businesses with empty name fields? Benches without the backrest tag? Between you and me, I don't like adding most of those just because who ever mapped the future originally didn't like doing it, but none of them are actually mapping errors that warrant warning someone about. 

> I mean, mappers aren't necessary aware this information is important and it's necessary to spend days to complete changesets that could be done correctly at first.

Did you ever think that maybe it's either not important to them, they don't have information, or might be planning on adding it later? People aren't required to add every possible tag to an object. In the meantime, just mapping a power pole without any extra tags is a "complete changesets. If you think more information should be added, cool. Then add it, but it's not the fault of the original mapper or an "incomplete changeset" just because you think other things should be added to the map.

**Comment by Adamant36** [comment]
BTW, I'm pretty sure there's already [Name-Suggestion-Index](https://github.com/osmlab/name-suggestion-index) presets for power infrastructure. If you want people nudged to add specific operator information that's probably the place to request it. This is repository is more about what tags Id Editor should support and it already supports the operator tag. So it's really not the proper venue for the question.

**Comment by flacombe** [comment]
> I mean, it would be if you add the operator tag yourself after the pole is mapped right?

We're dealing with 11 millions features + 8 millions for telecommunication networks.
I already spent **days** since 2021, January 1 to complete existing ones. As people add more poles, there are more objects to complete and everyone's volunteering time is limited. Currently the gap is wider than when it all began, so no it won't be ok.

This particular request allow the whole community to access free accurate imagery and make OSM visible in businesses that use to ignore it before, though the partnership the diary is about.
I wouldn't ask it if it doesn't worth it.

> I'm pretty sure it's something that could be done on the Name-Suggestion-Index's side though.

To me NSI only provides links between labels, wikidata and osm names. How would we specify a possible nudge for operator on `man_made=utility_pole` features there?

**Comment by Adamant36** [comment]
> We're dealing with 11 millions features + 8 millions for telecommunication networks.

That's slightly hyperbolic isn't it? There isn't 19 million power poles in France. Outside of that I'm not sure what telecommunication networks have to do with this issue since it's about power poles. 

> As people add more poles, there are more objects to complete and everyone's volunteering time is limited. Currently the gap is wider than when it all began, so no it won't be ok.

That goes for everything though. Including the person who your expecting to dig through government websites to find the operator of a power pole just so they can add it to the map without a warning. Why is your limited volunteer time more important then theirs? 

> This particular request allows the whole community to access free accurate imagery and makes OSM visible in businesses that use to ignore it before

Sorry, but I don't see the connection between tagging implementing a warning to tag operators on power poles and the community having access to free accurate imagery. Let alone why power poles having operator tags would make OSM more visible businesses. Perhaps you can enlighten me though?  

> I wouldn't ask it if it doesn't worth it.

I'm not really debating "worthiness" of implementing this since it's rather subjective. What I care about is if it's something that warrants a warning or not and IMO it doesn't because leaving out the operator tag isn't an error or bad tagging. Since that's warnings are for. To aid in fixing errors. Which I'm going to stick to unless you can convivence me otherwise. 

> To me NSI only provides links between labels, wikidata and osm names. How would we specify a possible nudge for operator on man_made=utility_pole features there?

Because if there is an entry for the operators of the power poles in the Name-Suggestion-Index then Id Editor will ask the user to "upgrade" the tags by automatically adding them with the preset.

**Comment by flacombe** [comment]
> That's slightly hyperbolic isn't it? There isn't 19 million power poles in France.

yes there are. 18 millions remains to be mapped and the point is to make editors the most efficient for that.

> Sorry, but I don't see the connection between tagging implementing a warning to tag operators on power poles and the community having access to free accurate imagery

It's the point of the partnership between the French OSMF local chapter and the mainland power distribution operator. We all (including operator's staff) map poles and they provide us with 5cm imagery.
It's very important to identify the operator of each pole as to allow him to use osm data (with all due respect to odbl terms).

I once again recommend to reread the diary entry.

> the person who your expecting to dig through government websites

Where did we expect that?
What about local signage, opendata and everyone's knowledge?

> Because if there is an entry for the operators of the power poles in the Name-Suggestion-Index then Id Editor will ask the user to "upgrade" the tags by automatically adding them with the preset

It has slightly been improved since the last time I looked at it.
I'll be thinking about adding them there, thank you.

**Comment by Adamant36** [comment]
> yes there are. 18 millions remains to be mapped and the point is to make editors the most efficient for that.

I meant currently mapped. Not how many there might or might not be mapped eventually. Since the purpose of warnings is to warn someone of a current issue. 

> We all (including operator's staff) map poles and they provide us with 5cm imagery.

Sure, but they are going to provide the imagery regardless of if Id Editor has a warning to add operator tags or not. 

> Where did we expect that?
What about local signage, opendata and everyone's knowledge?

I assume the "opendata" your referencing would be on a government website. Seriously, everyone doesn't magically have the knowledge of who the operator is. It's also not just out there in the ether and magically appears when the mapper thinks about it either. The person has to get the information from somewhere. 

> It has slightly been improved since the last time I looked at it.
I'll be thinking about adding them there, thank you.

At least something useful come out of the discussion

**Comment by flacombe** [comment]
Point of this request is to improve editors to encourage mappers to add operator=* on the yet un-mapped poles they create as to get nodes with `power=pole`+`operator=*` from the first version.  
We'll have an increasing flow of such creations until we reach ~11 millions power and 8 millions telecom poles.
It already began: https://taginfo.openstreetmap.org/tags/operator=Enedis#chronology

Existing poles without operator's name will be caught by time consuming clean up campaigns I mention upside. In some French districts or counties there already had 2 or 3 cleanup done since January 1.
The only mean I thought about was to nudge contributors, asking them for operator's name at the moment on they create those poles as to reduce the amount of feature that will have to be completed later, in addition to numerous informal communication, explanations, and so on...

> Sure, but they are going to provide the imagery regardless of if Id Editor has a warning to add operator tags or not.

They would recall it at a shorter term if we conclude on too few poles were added or with lacking information.

> Seriously, everyone doesn't magically have the knowledge of who the operator is

First of all it's written on the pole itself (as to not confuse technicians at first)
Secondly operators group themselves in a consortium to publish such knowledge in a user friendly fashion.

**Comment by Adamant36** [comment]
>  Existing poles without operator's name will be caught by time consuming clean up campaigns I mention upside.

That will be the case either way. It sounds like a better way to deal with outside of a warning is through a mapping party or MapRoulette challenge. The burden shouldn't be on random mappers who are adding power poles based on imagery in Id Editor to find or add the information though. Especially if it's not something they are already adding or want to. 

> They would recall it at a shorter term if we conclude on too few poles were added or with lacking information.

Do a mapping party or MapRoulette challenge then. Like I said though, I don't think it's on the average armchair user to add the information. 

> First of all it's written on the pole itself (as to not confuse technicians at first)
Secondly operators group themselves in a consortium to publish such knowledge in a user friendly fashion

I'm aware of where the information is. Surely though you get the difference between the information being on the pole or in a database and someone at home who's actually doing the mapping and getting the warning knowing it. I ask because for some reason you seem to have a serious disconnect about it.

**Comment by flacombe** [comment]
Mapping parties require to meet people on a very local area, which is nice by the way. However here, there are ~15 new people each month I don't even have time to contact (and I definitely shouldn't).

Maproulette could be a thing, like osmose currently is, but still rely on a very few maintainers versus an increasing population of contributors.

Between armchair and ground contributors, there are people like me who take pictures on the ground and contribute from my desktop.
I'd be happy to be nudged once and get informed of an additional useful information to seek for the next time.
There are no better media for that than directly in the editor, especially when beginners come at iD first.

**Comment by Adamant36** [comment]
> Mapping parties require to meet people on a very local area

Not really. I've been involved in a few that were global over Zoom myself. So they don't have to be. It really depends on who you want doing the mapping and what your wanting to map. You could easily do an online France wide mapatahon if it's that important. Sure, it might take time to contact people, but there's ways you can automate that and from what you've said it sounds like the alternative is more time consuming. 

Look it's mostly about balancing the pros and cons of each option. I don't personally think a warning is the best way to get what you want done, as there's no guarantee people won't just ignore it. With a mapathon or Maproulette you can at least link people to them and track how many edits they have made. Which if your worried about the French government taking away the images sounds like something you'd be interested in. Compared to telling them they should continue to let us use the images because you adding a warning to iD Editor that has zero way to track and probably won't be effective. That's just my opinion though. 

> There are no better media for that than directly in the editor, especially when beginners come at iD first.

I don't personally think adding operators to power poles is a good task for beginners. Especially if you care about quality. At least not without the operator information already built into iD Editor as a preset. Which it currently isn't. Otherwise, the rate of mistakes are likely to be so high you'll just have more in the long-term trying to clean it up. At least that's been my experience with similar projects.

**Comment by matkoniecz** [comment]
> We're dealing with 11 millions features + 8 millions for telecommunication networks.
> I already spent days since 2021, January 1 to complete existing ones.

It does not automatically mean that it is worth treating it as an error and raise warning.

At most, have a field making easier to fill it.

**Comment by flacombe** [comment]
It sounds we have different approach about this particular topic.

We've been testing this on JOSM for 3 months now without problems (and a few discussions with people looking to get the information).

Maproulette and remote sessions will be barely possible at short term due to lack of time. We'll see later.
Thank you for time involved here, this issue can now be closed.

**Comment by flacombe** [comment]
Hi all

I've gave Maproulette a try on a single French administrative region with this not yet discoverable challenge
https://maproulette.org/browse/challenges/22038

Experience isn't so great regarding this particular cleaning work.
Main issue is it's a bulk edit work and Maproulette requires to review every node independently.
Many clicks are needed to solve one single point while I'm able to fix many more points in a very less time with overpass+josm.
That doesn't mean Maproulette isn't a valuable tool in other contexts, it's not necessary to prove it's usefulness.

In this particular topic, asking for more people's time (to spread the clicking work on many more workers) to make a cleanup that could be avoided from the very beginning actually challenges my understanding.

**Comment by Adamant36** [comment]
> Main issue is it's a bulk edit work and Maproulette requires to review every node independently.

That's probably a good thing. Otherwise your doing a mass edit. That said, wouldn't it be the same way with a warning in iD Editor though? I.E. People would still have to be in the area, click the individual nodes, add the information Etc. Etc...The benefit of Maproulette is that it's at least organized around a central system and people won't have to just wonder randomly to the power pole to know it needs the tag. 

> In this particular topic, asking for more people's time (to spread the clicking work on many more workers) to make a cleanup that could be avoided from the very beginning actually challenges my understanding.

Same thing here. An iD Editor warning would have the same issue. If you want to do the work yourself and not involve other people then I really don't get what your aiming at here. Just skip the iD Editor warning or whatever and do an import.

**Comment by flacombe** [comment]
We're confusing many things here.

Grouping edits doesn't prevent to visually and independently check every feature we're about to edit.
The MapRoulette issue is an UX one, 3 clicks to edit a single feature, not an OSM etiquette issue.

> I.E. People would still have to be in the area, click the individual nodes, add the information

An editor warning you from the few first features you create without an important information expected for a national project is less time consuming than completing more than 10 000 nodes each weeks.

People don't have to be in the area, in the France case at least.

> If you want to do the work yourself and not involve other people then I really don't get what your aiming at here

I'm asking for the opposite.
I want to inform many people I can't reach for on other channels that an important tag is expected as to prevent *others including me* to be forced to make a costly cleanup afterwards.

I don't get what is you exact point here. This warning is live in JOSM and most of incomplete nodes come from iD, we don't have this issue with other editors.

**Comment by matkoniecz** [comment]
>  warning is live in JOSM and most of incomplete nodes come from iD

Is JOSM really complaining with warning level about any `power=pole`/`power=tower` without `operator` tag?

**Comment by flacombe** [comment]
Yes in France only.

https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules?action=diff&version=62
https://josm.openstreetmap.de/ticket/21010

**Comment by 1ec5** [comment]
> Is it possible to raise a warning in case of power=pole,tower located in France without operator=* on them please?
JOSM already has this quality check. It reduces a lot the amount of operator-unknown features and iD now remains the main editor encouraging this.

We’re a bit off-topic for this repository. id-tagging-schema only holds the presets that go into iD and some other tools. Validator rules are still maintained [in the iD repository](https://github.com/openstreetmap/iD/tree/develop/modules/validations).

>  This warning is live in JOSM and most of incomplete nodes come from iD, we don't have this issue with other editors.

The built-in validator is designed for things most mappers can reasonably be expected to resolve themselves without specialized knowledge, which is probably a more limited scope than JOSM’s validator. Unlike JOSM warnings, ignored iD warnings are perceived to count against users in [HDYC](http://hdyc.neis-one.org/) profiles, just like ignored Osmose warnings. That could explain why [your JOSM request](https://josm.openstreetmap.de/ticket/21010) was accepted with not much discussion but it has met with more skepticism now in the context of iD. A lay person faced with this warning would be inclined to suppress it by simply coping the `operator` from the power line, but that [may raise some eyebrows](https://www.openstreetmap.org/changeset/110880519) and would probably be incorrect in urban areas where utility poles are shared with other utilities. A mobile editor such as StreetComplete or Go Map!! would have users who are less likely to take such shortcuts.

iD also integrates with ImproveOSM, KeepRight, and Osmose for more thorough warnings aimed at mappers who are more dedicated to quality control. There are a lot of warnings supported by these validators but not by the one built into iD. If missing `operator` tags poses a significant practical problem for long-term maintenance of the database or for typical data consumers, then one of these QA tools may be better suited to the proposed warning. As it is, iD doesn’t even warn users about missing `operator` tags on things that are much more likely to be tagged with `operator`, such as `public_transport` features, 25% of which are tagged `operator`. It should probably be stated somewhere that not every project is important enough for the kind of real estate being requested here.

**Comment by matkoniecz** [comment]
>  If missing operator tags poses a significant practical problem for long-term maintenance of the database or for typical data consumers, then one of these QA tools may be better suited to the proposed warning. 

Osmose imports JOSM warnings already (though not checked is it doing it with France-specific ones).

**Comment by vinber** [comment]
> but if someone would enable it in Poland I would definitely treat it as unwanted spam (annoying to map, requires survey, little benefit if any).

yes, but it's not "someone which enabled it", it's a long time project with lot of discussion in french community.

**Comment by Adamant36** [comment]
> yes, but it's not "someone which enabled it", it's a long time project with lot of discussion in French community.

It was definitely "someone" who enabled it on JOSMs side. My guess is that the French community didn't do the code, merge it, or have anything to do with the warning being implemented outside of asking the maintainers of JOSM to enable it.

**Comment by flacombe** [comment]
> My guess is that the French community and their lots of discussion didn't do the coding, merge it, or have anything else to do with the warning

If you read it correctly, I'm the one who make this revision upon the advice of JOSM maintainers in the ticket.
https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules?action=diff&version=62

The background point is local community can control local context without disturbing anyone in other countries.
Obviously, I'm not asking for this warning to be rolled out worldwide, it would require further discussion. It's only about France here.

**Comment by Adamant36** [comment]
> Author is francois.lacombe not Klumbumbus.

I guess what's they get for using a 20 year old issue tracker. Anyway, I think my point still stands. "The French community" didn't do the PR. You did, sure your a part of the community, but for a universal warning like this there would have to be way more buy in from French mappers IMO. I know personally that as a mapper in Northern California if "the community"  in Southern California decide to force a warning on me for something like this I'd probably take the same stance @matkoniecz would about it if there was a similar warning in Poland..

More on topic, does Id Editor even have the ability to geographically limit warnings? I know the NSI can with tag recommendations, but has it been applied to other things in Id Editor besides presets?

**Comment by tyrasd** [comment]
> > Is JOSM really complaining with warning level about any power=pole/power=tower without operator tag?
> Yes in France only.

Please correct me if I'm wrong, but I think one manually needs to enable the "France specific rules" in the "Data validator" preferences dialog (see screenshot below) for this to actually happen. At least for me these rules were not active by default when mapping in France. This would mean that a "regular" mapper, mapping using JOSM in France will not get a warning about the missing operator tag on power poles and towers. Only experienced users who are aware of the special extra validation rules would be able to see them.

<img src="https://user-images.githubusercontent.com/1927298/148574745-1d36cf11-baab-4f48-92b0-50cb0dbf2809.png" width="500">

Since iD doesn't support custom optional validation rules, this is not something I can implement easily on iD right now.

**Comment by matkoniecz** [comment]
> Only experienced users who are aware of the special extra validation rules would be able to see them.

And only ones willing to enable them and keep them enabled would get this kind of warning.
