### ISSUE TITLE
Remove HTML tags from generated file

### ISSUE THREAD

**Issue by tordans** [openstreetmap/id-tagging-schema#246]
There was an issue in GoMap https://github.com/bryceco/GoMap/issues/562 where HTML was showing up from  the generated JSON https://github.com/openstreetmap/id-tagging-schema/blob/bde8a416c80cbbb27a0ad36df3c6dcec3151ec8b/dist/translations/de.json#L60.

I removed the HTML Tags from Transiflex https://www.transifex.com/openstreetmap/id-editor/translate/#de/$/11976906?q=text%3Adesignated

However, the previous translation was 3 years old and the Issue only now came up. So I wonder, if something changes.
![image](https://user-images.githubusercontent.com/111561/136007696-aabf6c8b-bf56-4ee3-af97-dcd2c2eca249.png)

Or even more importantly: 

**I think the generated JSON should be cleared of all HTML translations and only include text.**

**Comment by tyrasd** [comment]
I don't think anything actually changed with respect to this in the past year(s). Not sure why this one didn't get noticed earlier… :thinking: 

I agree that translations should never contain HTML markup. But I also don't think that this repo should clean up the translation strings in some way. Otherwise there could be corner cases like for example when a text contains some kind of `<placeholder>` which would get broken by such a cleanup.

PS: https://github.com/openstreetmap/iD/pull/8817 might also be relevant.
