### ISSUE TITLE
Add layby to parking field

### ISSUE THREAD

**Issue by boothym** [openstreetmap/id-tagging-schema#287]
https://wiki.openstreetmap.org/wiki/Tag:parking%3Dlayby 

Would be useful to have this value added to the dropdown as it's a useful refinement to a parking object. This is actually used more often than some of the values already included in the parking tag.

https://github.com/openstreetmap/id-tagging-schema/blob/278b0441afe4d34993ac9a409a168241a4a69efd/data/fields/parking.json#L6-L15

**Comment by tordans** [comment]
Sorry for being late with feedback here after @tyrasd just pushed the requested change.

I just wanted to make sure we have this value explained properly. Or, in case the explanation leaves room for misunderstanding, maybe we should scope this value to the UK where the Wiki says it is most common?

Mind, that we cannot really look just at the usage numbers, because the tag was (miss)used in the past (more below).

https://github.com/openstreetmap/id-tagging-schema/commit/728cceb27407072c10219f6ed01e0d874b5fb2e3#diff-7d8184601e0b81f317066fbca4f83d67d318a784b0655512f40587c760ac7ad0R16 explains the value with "Turnout" which I don't know as a term (and Google Translate is not help). Is this a term signifying "rest area" or "parking to take a break"?

Background: I remember a recent proposal and discussion that tried to untangle the lay(_|-)by values. Mind, that this values here for key `parking` (not key `parking:lane`) is fine; this is just to document the previous and recent discussion and make sure mappers don't misunderstand the value.

- https://wiki.openstreetmap.org/w/index.php?oldid=2066642#Relation_to_other_parking.3D.2A_values tries to untangle a bit of history, concluding in deprecating the value for the `parking:lane` schema
- https://wiki.openstreetmap.org/wiki/Key:parking:lane#Parking_position deprecates the tag for `parking:lane` and also stresses the rest area character of `parking=layby`
- https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking explains it with "take a break"
  > A minimal parking facility alongside a major road where motorists can take a break en-route to their destination.
- https://wiki.openstreetmap.org/wiki/Tag:parking%3Dlayby tries to cleanup old tagging with the "when not to use" headline

**Comment by tordans** [comment]
> If you're not familiar, an example of a layby can be found here: https://www.mapillary.com/app/?pKey=1558477194356640

If it where not for the `[P]` sign I would for sure map this as a `highway=passing_place`.

---

Looking at the map, I wonder if we should start by scoping the value to GB and wait for the Finish(?) community to request it as well https://taginfo.openstreetmap.org/tags/parking=layby#map.

**Comment by boothym** [comment]
>If it where not for the [P] sign I would for sure map this as a highway=passing_place.

If it was a narrow road then yes, but it's a two lane road though so you don't need a passing place 😉

**Comment by tyrasd** [comment]
> "Turnout" which I don't know as a term

I went with the term Wikipedia mentions on https://en.wikipedia.org/wiki/Rest_area#Lay-bys: _‘Equivalent terms in the United States are "turnout" or "pullout".’_

I also thought about labeling it as _rest area_, but I think that could be confusing in case of larger rest areas: _“For larger rest-areas separated from the main road with its own service roads and other facilities, consider […] map the parking facilities there with parking=surface […]”_

> "turnout" which nobody British will understand, although I assume it can be translated to en-GB?

yes, it can be translated on transifex

**Comment by tyrasd** [comment]
> As for the translation - is there an en-ie translation

As far as I can see, there is currently no dedicated `en-ie` translation active on transifex for the [iD editor project](https://www.transifex.com/openstreetmap/id-editor/languages/) (which includes also the presets. It could be added if you like (and if the Irish OSM community agrees).

I've also renamed the string to _Turnout / Lay-By_ in 969421dce242db2e29cb1d3736b31b44d9fee18f for now.

**Comment by 1ec5** [comment]
Oh, I missed this discussion before posting https://github.com/openstreetmap/id-tagging-schema/commit/969421dce242db2e29cb1d3736b31b44d9fee18f#r64054862. “Lay-by” is so unknown and odd-sounding in American English that I’m sure it’ll cause any American English speaker who knows what “turnout” means to second-guess themselves. Instead of overloading the American English localization with terms from around the world, why not create an en-IE localization and invite the Irish community to help override Americanisms with local vocabulary? I’m sure “turnout” isn’t the only thing that Irish English speakers would find confusing or off-putting. (As far as I know, its spelling is closer to British English anyways.)

**Comment by tyrasd** [comment]
Hey. There were a few different reasons behind me adding the term "lay-by" in this label:

* I wanted to wait for a confirmation of the Irish community if they actually want to maintain a translation.
* The regular `en` locale also needs to work for people who have set up the generic `en` in their OS/browser (see also [#288 (comment)](https://github.com/openstreetmap/id-tagging-schema/pull/288#issuecomment-985517274)). This could be everywhere on the planet.
* The default `en` locale is also the basis for translators, so being a little over-specific helps to avoid translation errors.

I see now that my solution is not optimal for Americans. Apologies for that. I have an idea which could be a solution which works for everyone: Why not just add a dedicated `en-US` locale? More information about this proposal is outlined in #357. What do you think?

**Comment by westnordost** [comment]
These are the source strings for StreetComplete for street parking (parking:lane):

https://github.com/streetcomplete/StreetComplete/blob/b77f72070aec92efbd3d8524e3826e9ce9db1225/app/src/main/res/values/strings.xml#L1168-L1180

**Comment by 1ec5** [comment]
> I wanted to wait for a confirmation of the Irish community if they actually want to maintain a translation.

For what it’s worth, there are currently 58 languages without any translators on Transifex, not counting the ones lacking active translators. It’s been this way for years. Do you see any downside in creating a localization as a holding place for overrides we already know we need, and allowing the other strings to be inherited from the main English localization?

**Comment by tyrasd** [comment]
Good point, we can already add the language on transifex. But I would need to know who to add as a _Language Coordinator_, since that seems to be required by transifex to add a new language. @boothym – would it be OK if you manage that? If I recall correctly, the language coordinator can then add more collaborators to translate the respective strings in that locale.

**Comment by 1ec5** [comment]
Transifex doesn’t require anyone to be on a language team in order to add a new language. It just displays a little label complaining when there are no translators. A coordinator can help manage requests by other users to join their translation team. However, I’m pretty sure iD’s maintainers over the years have just approved every request to join a language team. (By contrast, they would decline most requests for new regional locale, because Transifex’s confusing UI misleads users into thinking they need to request a new regional locale just to do any translation.)

**Comment by 1ec5** [comment]
Going back to the original topic, I’m getting the sense that “lay-by” in British English is actually [a very broad term](https://commons.wikimedia.org/wiki/Category:Lay-bys_in_England) that can cover everything from [a wayside rest area](https://commons.wikimedia.org/wiki/File:Layby_on_the_A361_-_geograph.org.uk_-_304884.jpg) with [basic concessions](https://www.herefordtimes.com/news/18181423.new-burger-van-starts-serving-herefordshire-lay-by/) all the way down to [a short parking lane](https://commons.wikimedia.org/wiki/File:Lay-by,_Tamlaght_Road,_Omagh_-_geograph.org.uk_-_1473933.jpg) reminiscent of a [passing place](https://commons.wikimedia.org/wiki/File:Single_track_road_-_geograph.org.uk_-_749610.jpg) or [emergency bay](https://commons.wikimedia.org/wiki/File:Bundesstra%C3%9Fe_31_in_Freiburg-Waldsee_an_der_Fu%C3%9Fg%C3%A4nger%C3%BCberf%C3%BChrung_zum_Kunzenweg_mit_Nothaltebucht.jpg). Is this true, or are these cases just called “lay-by” by analogy with a “typical” lay-by?

[The wiki](https://wiki.openstreetmap.org/wiki/Special:PermanentLink/2212859) has defined `parking=layby` quite differently, constraining it to what American English would unambiguously call a “turnout”. Do British English and Irish English have a more precise word for _this kind_ of lay-by, perhaps by adding a qualifier like “away from the carriageway”?

(Also being discussed [in OSMUS Slack](https://osmus.slack.com/archives/CBK3JLUJU/p1642730680007200).)
