### ISSUE TITLE
Add parking:orientation key and field

### ISSUE THREAD

**Issue by AntMadeira** [openstreetmap/id-tagging-schema#291]
I would like to request to add the key parking:orientation=* key with its corresponding field in the parking preset.

[https://wiki.openstreetmap.org/wiki/Key:​parking:orientation](https://wiki.openstreetmap.org/wiki/Key:parking:orientation)

**Comment by tyrasd** [comment]
#73 had already added this field to the "street side parking" preset, which is where the `parking:orientation` is used most often.

According to the osm wiki page, the tag could also be used with `parking=lane` (albeit to a limited extent, since mostly only the value `parallel` would be applicable). But iD doesn't have a special preset for parking lanes, and I guess that's not particularly a bad thing, since that tag competes with mapping lane-parking as an attribute of roads, which is also not yet supported by iD.
