### ISSUE TITLE
Add a preset for avalanche transceiver training zone and checkpoint

### ISSUE THREAD

**Issue by letypequividelespoubelles** [openstreetmap/id-tagging-schema#379]
### Description

Hi, 

A new tag has been approved for [avalanche transceiver](https://wiki.openstreetmap.org/wiki/Key:avalanche_transceiver) training zone and checkpoint. Would it be possible to have a preset in the iD editor for this two objects ? 
Thanks a lot !

**Comment by tyrasd** [comment]
Hey. Thanks for the suggestion.

Currently, I'm a bit hesitant to include this because the tag is only used 23 times in total and globally. This is likely simply because the tag is still new. I would be happy to reconsider adding this tag when usage numbers are substantially higher at some point in the future.
