### ISSUE TITLE
Don't suggest last_checked or lastcheck when creating tags in iD

### ISSUE THREAD

**Issue by dreua** [openstreetmap/id-tagging-schema#410]
When I misguidedly start typing `last`as a new tag, iD suggests `last_checked` and `lastcheck`, both of which should not be used in favor of check_date. (Correct me if I got that wrong.)

**Comment by tordans** [comment]
Please share a screenshot of what you see and url.

**Comment by dreua** [comment]
![Screenshot from 2022-02-28 23-43-43](https://user-images.githubusercontent.com/15114715/156070881-0cedbef5-7056-4582-847a-cf0a1842b56a.png)
URL: https://www.openstreetmap.org/edit#map=19/49.98549/8.22857

**Comment by tordans** [comment]
@dreua the "Tags" area you are using is intended for experienced mapper that want to work with OSM data without the help of the Fields and Feature Types (Presets). So it is by design that is allows you to add all manner of tags. The autocomplete is based on a top x list of results from tag info. 

This repository is only about the area above, the "Feature types" / Presets.

The "Tags" area is part of the [iD project](https://github.com/openstreetmap/id) itself.

Personally, I would support an effort to consolidate all those different check date keys to `check_date`. But that would be something for a deprecation proposal for the tagging mailing list … — Once such a proposal is accepted, this Repo would hold the deprecation rule that updates deprecated tags.

**Comment by dreua** [comment]
Alright thank you for the input.
