### ISSUE TITLE
Rename "Closed road" to something more appropriate

### ISSUE THREAD

**Issue by RudyTheDev** [openstreetmap/id-tagging-schema#443]
"Closed road" is a bad label for `highway=construction` because a closed road does not imply "under construction". It could easily be interpreted to mean something like `access=no` or `abandoned:highway=*`, nor is this something one would obviously select from search results, like at least "road under construction".

And the bigger issue is that any `highway=construction` is called "road", whether a path or bridge or anything else. So a pedestrian bridge appears as "closed road".

Before trying to figure out the best way to name and/or separate this, is there a rationale for this label?

**Comment by bhousel** [comment]
> Before trying to figure out the best way to name and/or separate this, is there a rationale for this label?

context is here:  https://github.com/openstreetmap/iD/issues/5599

This preset isn't for a "Road under construction"

It's for something like a bridge out or other medium-to-long term closure that affects routing.
The important thing is to make it simple for people to tag roads that are closed.

**Comment by RudyTheDev** [comment]
> This preset isn't for a "Road under construction"

What do you mean? It is set for `highway=construction`, which is by definition for "roads/paths under construction". Something is being built or renovated and inaccessible for a longer period. That is not the same as "road closed", which can be for various reasons and construction is only one of them. The label is wrong.

> It's for something like a bridge out or other medium-to-long term closure that affects routing.

That is not what `highway=construction` means. That's just `access=no`, which all routers know about.

**Comment by bhousel** [comment]
The preset matches on both `highway=construction` and `access=no`
(please read the discussion on the ticket I linked to)

https://github.com/openstreetmap/id-tagging-schema/blob/9fdecc983443ce75185c2923caae9f7703f2cae4/data/presets/highway/construction.json

**Comment by RudyTheDev** [comment]
Yes, I have read the discussion. I had even commented on it. I am asking about the label specifically. I see you implemented the "Closed road" label, but you never explained why something that requires `highway=construction` has a label that implies more than construction. Having `access=no` does not change the meaning of `highway=construction`. It's still a "way under construction" but with an explicit (presumably, surveyed) access tag. This makes it one type of "closed road", yes; but a "closed road" can be closed for _different_ reasons. The label makes it sound like it applies to _any_ closed road. This is misleading.

**Comment by bhousel** [comment]
> Having `access=no` does not change the meaning of `highway=construction`

It absolutely does.

**Comment by 1ec5** [comment]
> > Before trying to figure out the best way to name and/or separate this, is there a rationale for this label?
> 
> context is here: [openstreetmap/iD#5599](https://github.com/openstreetmap/iD/issues/5599)
> 
> This preset isn't for a "Road under construction"
> 
> It's for something like a bridge out or other medium-to-long term closure that affects routing. The important thing is to make it simple for people to tag roads that are closed.

“Under Construction” is problematic because people are inclined to use it on roads that are only undergoing minor construction, like widening or restriping. On the flip side, “Closed Road” is also problematic because plenty of roads are closed to some or all for reasons other than construction. But long-term road closures are more nuanced than a preset alone can adequately describe.

As I understand it, the preset is applicable if and only if both conditions are satisfied:

* The road is under construction – the user can only indicate this using the preset.
* The road is off-limits – the user normally indicates this using the Access field, not a preset.

Is there a name for the preset that better communicates both of these requirements? “Road Closed for Construction”?

**Comment by tyrasd** [comment]
I agree with @RudyTheDev. Whether a road is _closed_ to traffic or not should be mapped with the corresponding `access` tag, independently of the value of the `highway` tag. The [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dconstruction) also clearly states that `highway=construction` should only be used for roads/paths/etc. which are under construction. To mix these two concepts into the current [_Closed Road_](https://github.com/openstreetmap/iD/issues/5599) preset was a mistake IMO.

> “Under Construction” is problematic because people are inclined to use it on roads that are only undergoing minor construction, like widening or restriping.

I think this is much less of an issue in practice, because the used symbology (icon, map rendering) quite clearly indicates that the road in question should be considered impassible.

**Comment by 1ec5** [comment]
> I think this is much less of an issue in practice, because the used symbology (icon, map rendering) quite clearly indicates that the road in question should be considered impassible.

Maybe this isn’t so clear to the novice mappers I’ve seen use this preset to map short-term lane closures and such. Not everyone reads the wiki before urgently retagging a road as being closed for construction. The kind of sign depicted in the icon is the kind that’s also used for short-term lane closures and other roadwork. I appreciate the parallelism between “Railway Under Construction” and “Road Under Construction”, but it doesn’t seem like a big deal to add another word to emphasize the substantial nature of the construction.

[![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/FEMA_-_22900_-_Photograph_by_Marvin_Nauman_taken_on_01-27-2006_in_Louisiana.jpg/640px-FEMA_-_22900_-_Photograph_by_Marvin_Nauman_taken_on_01-27-2006_in_Louisiana.jpg)](https://commons.wikimedia.org/wiki/File:FEMA_-_22900_-_Photograph_by_Marvin_Nauman_taken_on_01-27-2006_in_Louisiana.jpg)

Regardless, would you consider moving the Allowed Access field higher up so that mappers realize they have the ability (and possibly the obligation) to add an appropriate access tag to a road under construction? Currently it’s buried quite a ways below the fold.

**Comment by tyrasd** [comment]
> add another word, like “Major”

I don't know. Something like "Road Under Major Construction" or "Road Under Construction (Major)" would look a bit odd to me at first glance… Doesn't that a whole lot on unnecessary ambiguity to the name? For example, can a construction be considered major if the road which is under construction is only a minor road or path?

Should we just try it as is for now and readjust the name should we find that many novice mappers use it incorrectly in practice?

>  moving the Allowed Access field higher up

Sure! That's a good idea. I'll swap it with the "note" field.

**Comment by RudyTheDev** [comment]
> routers still treat as passable

Is this actually true? I have not seen my routes go through `highway=construction` and almost none of them have any sort of `access` tags here. I don't know what routers they use underneath, but I have always assumed they ignore construction stuff. After all, it's not like they can blanket follow `highway=` because they would quickly run into pedestrian-only paths and such. So including `construction` in routing would have been a deliberate choice.

Anyway, here is some limited naive testing I did to see what routers do (because I could be completely wrong about something I assumed long ago). I'm trying the ones from https://wiki.openstreetmap.org/wiki/Routing/online_routers that work and have an online tool.

I picked a random spot I found with a `highway=construction` (and `construction=residential` so it won't assume something invalid) road and no `access` tag that's clearly a shorter/faster route: https://www.openstreetmap.org/way/693836135#map=17/52.53713/-0.25284 :

![Area in editor](https://user-images.githubusercontent.com/3857299/168103133-d459081d-e444-4bbf-9ea0-6ed0cc3788b7.png)

These are my results:

OSRM (also one of option on OSM main page)
![OSRM](https://user-images.githubusercontent.com/3857299/168098697-bf148ba5-a9cc-49d4-ae14-66229f761652.png)

GraphHopper (also one of option on OSM main page)
![GraphHopper](https://user-images.githubusercontent.com/3857299/168098689-09ce9bc4-b905-448f-9311-a240b8c2c38e.png)

OpenRouteService
![OpenRouteService](https://user-images.githubusercontent.com/3857299/168098677-a80587d9-1024-4a79-9793-eeefad0d0146.png)

BRouter (car)
![BRouter car](https://user-images.githubusercontent.com/3857299/168098691-09a03557-4ea0-4d86-84d1-f4098dc41bb4.png)

BRouter (bike)
![Brouter (bike)](https://user-images.githubusercontent.com/3857299/168099699-5844190b-e5b2-49b7-a0e2-09a3f3bcb1d4.png)

Routino
![Routino](https://user-images.githubusercontent.com/3857299/168098698-b79a9847-2d1b-4fa8-9bcd-d3c7f5f841b2.png)

Valhalla (car)
![Valhalla (car)](https://user-images.githubusercontent.com/3857299/168101524-513c17b5-767d-4400-81f7-3e8c8d6fafd5.png)

Valhalla (bike)
![Valhalla (bike)](https://user-images.githubusercontent.com/3857299/168101541-cc9392fb-f145-47b3-b321-1211fc4892bb.png)

None of these examples routed cars through construction (and one routed a bike through it, which is nice to see because it means the "raw" route is theoretically valid and I didn't pick an invalid example). Obviously, it's a very limited test scenario (how many routers are there?) But these look like major routers, so I would conclude routers don't normally route through construction. Am I wrong in my thinking? I don't know how else to test routers en masse across different scenarios.

**Comment by bhousel** [comment]
> None of these examples routed cars through construction (and one routed a bike through it, which is nice to see because it means the "raw" route is theoretically valid and I didn't pick an invalid example). Obviously, it's a very limited test scenario (how many routers are there?) But these look like major routers, so I would conclude routers don't normally route through construction.

Thanks for testing!  I was told in 2018 that we needed the `access=no` tag, but it looks like now we don't.

Regardless,  "Closed Road" is still a much better name for preset than "Road Under Construction".  We will definitely see users misuse it once this goes live.

**Comment by 1ec5** [comment]
> I don't know what routers they use underneath, but I have always assumed they ignore construction stuff. 

I’m also unaware of any router or routing profile that currently routes over `highway=construction`. A typical router wouldn’t even bring an unrecognized `highway` value into the routing graph, so including `highway=construction` would be a deliberate choice. The OSRM project did experience some painful back and forth some years ago on whether to route over roads tagged as e.g. `highway=residential` `construction=yes`. Ultimately they decided to discard such ways as tagging errors not to be encouraged: Project-OSRM/osrm-backend#4230 Project-OSRM/osrm-backend#4462. The wiki [raises the possibility](https://wiki.openstreetmap.org/wiki/Special:PermanentLink/2307700#How_to_map_the_completion_of_road_construction) that a road might be closed for construction but remain open for pedestrians and cyclists. However, to me that seems like a case for `motor_vehicle=no` and `construction=*` rather than `highway=construction`.

Now that the preset no longer adds `access=no`, will the initially empty Allowed Access field have “yes” placeholders throughout, or does iD somehow know that `highway=construction` implies `access=no`? People [do gravitate](https://wiki.openstreetmap.org/wiki/Talk:Tag:highway%3Dconstruction#Impassable) toward an “under construction” preset for minor construction, so it isn’t a purely theoretical concern, though it’s hard to know whether the issue is prevalent.

**Comment by tyrasd** [comment]
> Now that the preset no longer adds `access=no`, will the initially empty Allowed Access field have “yes” placeholders throughout, or does iD somehow know that `highway=construction` implies `access=no`?

It does not yet take this into account, but would actually be a very good addition to be implemented in iD alongside the change in the presets. :+1:

**Comment by RudyTheDev** [comment]
> be a very good addition to be implemented in iD

Random question, but how is it done for other presets? Like, when you add a "Cycle Path" https://github.com/openstreetmap/id-tagging-schema/blob/dd1705e5a7b1b3e83fe37eeb1ad91a45605c0d04/data/presets/highway/cycleway.json where do these "yes", "no", "designated" values come from? I had always assumed it's part of the preset.

![implied](https://user-images.githubusercontent.com/3857299/168132144-336c5d70-ebd3-4746-b088-96f9c17d83e5.png)

![actual tags](https://user-images.githubusercontent.com/3857299/168132442-567d7b95-ec4b-4de8-b30b-06a2bb50c4d9.png)
