### ISSUE TITLE
Presets for climbing ladder and safety cable

### ISSUE THREAD

**Issue by rivermont** [openstreetmap/id-tagging-schema#494]
`ladder=yes` and `safety_cable=yes` contain important information for hikers on mountainous trail routes, though criminally undertagged. `ladder=yes` could also use a integer field for `rungs=`.

**Comment by tordans** [comment]
Some links: 

* Wiki https://wiki.openstreetmap.org/wiki/Key:ladder
* Approval https://wiki.openstreetmap.org/wiki/Proposed_features/Safety_measures_on_hiking_trails
* Usage https://taginfo.openstreetmap.org/keys/ladder#overview 2.3k
  * But only [359 in combination with `highway`](https://taginfo.openstreetmap.org/keys/ladder#combinations), if I read the numbers correctly

**Comment by tordans** [comment]
I looked into this taggging a while back and was amazed that this was approved as tagging. There was likely a discussion why one would have a tag like `highway=stairs` but not `highway=ladder`? To me, a ladder is much more like stairs then they are like a path… — Maybe someone could summarized this discussion or link it?

For me, this tagging is a case where data consumers should be part of the decision to promote it (with a preset). This is – als always – a chicken-egg-topic, but more so here IMO, since the fallback tagging (highway) has a certain expectation (implicit tags) which is not met by a ladder.

FYI, `[highway=ladder](https://taginfo.openstreetmap.org/keys/highway#values)` has no usage, not once, so at least it is consistent :-).

**Comment by rivermont** [comment]
A ladder is not much like stairs in a hiking since; ladders are inherently vertical in nature while stairs carry you horizontally and vertically.

The reason only 360 are in combination with `highway` is because 2k are nodes, as they should be.

**Comment by tordans** [comment]
> A ladder is not much like stairs in a hiking since; ladders are inherently vertical in nature while stairs carry you horizontally and vertically.

Yes, which is exactly why I feel that having it as a "modifier" on highway=path is a non-ideal tagging. Data consumers need to look very closely to consider this kind of "barrier".

The wiki says
> This tag is added to an existing [highway](https://wiki.openstreetmap.org/wiki/Key:highway)=[path](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath). Short sections can be tagged as node node, longer sections as way way.

To make it easier for data consumers to "notice" the ladder, maybe adding something like "`barrier=ladder`" ([used 7 times](https://taginfo.openstreetmap.org/keys/barrier#values)) or `hazard=ladder` ([not used at all](https://taginfo.openstreetmap.org/keys/hazard#values)).

Again, I am not trying to modify the tagging practice, just trying to figure out if the current tagging is ready for "prime time" (or if it needs to be discussed and evolved further by the community, first).

(Btw, it is more like [`steps`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dsteps) than like highway in the sense that both have a `step_count` ("rungs" for ladders?).)

But I might be overthinking this. We have other presets that are the first time an important but not-much-used tag and not-ideally-defined-tag gets promoted because it is specified this way by the community and "gets the job done". Which will give it visibility and increase usage by consumers. — Lets see what others think.

---

On a more practical node:

**Notes:**

We would need a preset for the stand alone ladder on a way. So those nodes should not be place without being attached to a way. And they should have a good icon.

**Ways:** 

And we need a preset for a segement of path being tagged as ladder. Only for `highway=path` I assume. Maybe as part of the structure select in iD [(<img width="100" alt="" src="https://user-images.githubusercontent.com/111561/173172872-17f6634a-ce32-437c-b7e8-824054f2b6ee.png">)](https://user-images.githubusercontent.com/111561/173172872-17f6634a-ce32-437c-b7e8-824054f2b6ee.png)? Would that be possible? But also as a searchable preset or at least search terms for the existing path-preset.

**Comment by tordans** [comment]
I think we can close this in favor of https://github.com/openstreetmap/id-tagging-schema/issues/1054 and which is being worked on in https://github.com/openstreetmap/id-tagging-schema/pull/1153.

**Comment by tordans** [comment]
@rivermont on the topic of `safety_cable=yes` I think it best to open a new issue if needed and base this on the latest discussions that happened while the `highway=ladder` proposal was discussed/accepted.
