### ISSUE TITLE
Allow tagging signalized but unmarked pedestrian crossing

### ISSUE THREAD

**Issue by 1ec5** [openstreetmap/id-tagging-schema#507]
For completeness, there should be a preset or field that allows the user to indicate that a pedestrian crosswalk is signalized but unmarked.

## Rationale

As of #192 #368, this repository has a set of presets to express each of these pedestrian crossing configurations:

* Crossing with no road markings and no traffic signals (`crossing=unmarked`)
* Crossing with road markings but no traffic signals (`crossing=marked`)
* Crossing with road markings and traffic signals (`crossing=traffic_signals`)

However, there’s no affordance for tagging crossings with traffic signals but no road markings.

This configuration is standard and commonplace in some regions: https://github.com/openstreetmap/id-tagging-schema/issues/408#issuecomment-1061225441. Where it occurs, it is important to distinguish from a crossing with traffic signals and road markings, because the lack of road markings creates a higher risk profile for pedestrians, especially where there are unprotected left turns. One can imagine a pedestrian router applying the same penalty as for marked, signalized crossings, while a car router issues the same alert as for unmarked, unsignalized crossings.

## Tagging

The [most common](https://overpass-turbo.eu/s/1jvg) tag combination for this configuration is `crossing=unmarked` `crossing:signals=yes`, with 78 occurrences globally. This is likely an undercount, because the [`crossing:signals`](https://wiki.openstreetmap.org/wiki/Key:crossing:signals) key description page was created only a few weeks ago despite being [proposed](https://wiki.openstreetmap.org/wiki/Proposed_features/crossing:signals) several years ago. It’s quite likely that a lot of unmarked, signalized crossings are being tagged as just `crossing=unmarked` or just `crossing=traffic_signals`, losing valuable information.

Even if we assume that this configuration is limited to the United States (which is [false](https://www.openstreetmap.org/way/1062779200)), it is still common enough to merit support in this repository. `crossing=unmarked` `crossing:signals=yes` represents 1% of [all `crossing:signals` usage in the U.S.](http://taginfo.geofabrik.de/north-america/us/keys/crossing:signals) At this rate, over 2,000 of the `crossing=traffic_signals` that have been tagged so far in the U.S. could conceivably be candidates for `crossing:signals=no`. Of course, that can only be a rough estimate, because so much data has already been lost through the adoption of `crossing=traffic_signals`.

## Design

One approach would be yet another set of presets, i.e., “Unmarked Crossing With Pedestrian Signals”. The existing “Crossing With Pedestrian Signals” preset would be renamed to “Marked Crossing With Pedestrian Signals” to avoid confusion. This unwieldy name would accurately reflect the approved antipattern of cramming multiple orthogonal aspects into a single tag.

A cleaner approach would be to add a “Pedestrian Signals” checkbox field to the “Marked Crosswalk” and “Unmarked Crossing” presets. The existing “Crossing With Pedestrian Signals” preset might need to become unsearchable, to avoid a situation where the editor forces the user to choose between two functionally equivalent but very different-looking tagging combinations.

**Comment by tyrasd** [comment]
> Tagging

The problem here is that there doesn't yet exist an approved tagging schema for such crossings. Since the [proposal for `crossing:signals`](https://wiki.openstreetmap.org/wiki/Proposed_features/crossing:signals) would deprecate the existing tag `crossing=traffic_signals`, I'm very hesitant to include this in the tagging schema before the community has reached a decision on the proposal as a whole.

Please discuss this on the dedicated community channels for tagging, and try to bring the tagging proposal to a conclusion. When that is done, we can continue the implementation details here.

**Comment by 1ec5** [comment]
That’s fair, but in the meantime, we do have a bit of a problem with `crossing=traffic_signals` now being promoted so prominently. It may be a (kind of) approved tag from eons ago (with lots of asterisks), but including it without the antonym means iD is promoting dataloss in some regions. I think this means the migration path in the proposal will need to be more aggressive than it would be if the `crossing:signals` key were adopted piecemeal for only the crossings that aren’t adequately served by the approved tags.

**Comment by 1ec5** [comment]
As a starting point, can we consider renaming “Crosswalk With Pedestrian Signals” to “Marked Crosswalk With Pedestrian Signals”, to reflect the actual documented meaning of the tag? I don’t think that requires a new proposal, because it’s consistent with the original approved one.

**Comment by tyrasd** [comment]
Unfortunately, the tag [`crossing=traffic_signals`](https://wiki.openstreetmap.org/wiki/Key:crossing#Approved_tags) is documented to be used on any _crossing with traffic signals_ which _may or may not feature road markings_. Renaming the preset would contradict the wiki. :unamused:

**Comment by 1ec5** [comment]
Oof, yep, you’re right. So for now, there’s nothing to be done about the potential for `crossing=unmarked` `crossing:signals=yes` to be changed to `crossing=traffic_signals` by mappers unaware of the hidden `crossing:signals=yes` tag but aware of the prominent “Crossing With Pedestrian Signals” preset?

**Comment by tyrasd** [comment]
Not really, except for bringing the new tagging proposal further along.

Maybe a very slight positive take on this topic: Since the preset for `crossing=unmarked` is simply called _"Unmarked Crossing"_ (and not _"Unmarked Crossing Without Traffic Signals"_), it leaves the opportunity open for mappers to choose it over the _"Crossing With Pedestrian Signals"_ preset if they experience that the lack of markings is the more important / most distinctive property of a particular crossing for them.

**Comment by tyrasd** [comment]
> Many occurrences of `crossing=traffic_signals` `crossing:signals=yes` began as `crossing=marked`/`unmarked` `crossing:signals=yes`

For reference: Looking at the data, there have only ever been 12 occurrences of features having the tag combination `crossing=traffic_signals` + `crossing:signals=yes` in OSM. I wouldn't draw too many conclusions from such a small sample (especially when considering the relatively large number of 1.7k objects with `crossing=marked` + `crossing:signals=yes`).

**Comment by nbolten** [comment]
> I am interested in taking a revised version of @nbolten’s 2019 proposal to a vote. But there’s been so much skepticism from Europe about the unmarked/signalized configuration that I think it would be necessary to first demonstrate the prevalence ahead of any project-wide vote. As one of the top users of `crossing=traffic_signals` globally, and formerly one of its biggest proponents, I’m focused on replacing my usage of that tag in favor of `crossing:signals`, which didn’t exist back when I did most of my crosswalk classification tagging.

I'd be happy to help spruce up the proposal! The non-orthogonality of pedestrian signals vs. markings is a longstanding issue for getting these things reliably mapped - and for providing useful, or even understandable, instructions to mappers.

In my opinion, the proposal would benefit from having several examples where the current schema fails but the proposed schema would work. Also, examples where both schemas work, to show that it wouldn't break anything. Do any folks have some favorites off the top of their heads? I had one in New York, NY that I used to show people.

**Comment by bgo-eiu** [comment]
This is the favorite that comes to mind for `crossing:signals=yes` + `crossing=unmarked` - I was perplexed by it earlier this week. It's not immediately obvious until you try to cross, but the angles of the signal heads are perfectly aligned so that you can tell they are there walking up to it, but you can't actually see any of them when you're crossing. I was hopping back and forth a bit trying to work out if there was a way to cross that had something to do with what the signals were doing but I didn't figure it out, at least in the time I had. (Referring to the two facing each other, the one facing the camera here is visible at the crossing.)

![Weird crossing in Seton Hill (Baltimore, MD)](https://upload.wikimedia.org/wikipedia/commons/f/fd/Weird_crossing_in_Seton_Hill_%28Baltimore%2C_MD%29_-_Mapillary_%28377093650304918%29.jpg)

**Comment by 1ec5** [comment]
To clarify, I was referring to skepticism about whether the unmarked/signalized configuration can even legitimately exist in the real world – it does – but this is a good idea worth consideration. It looks like the possibility of a `crossing:marked` was analyzed [in the proposal’s wiki discussion](https://wiki.openstreetmap.org/wiki/Special:Diff/1856007) a few years ago.

**Comment by kaneap** [comment]
> 

You may be interested in the [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/crossing:markings) I made which attempts to capture these markings (as well as their style).

**Comment by tyrasd** [comment]
The [proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/crossing:markings) for the `crossing:markings` tag was recently approved.
