### ISSUE TITLE
Add support for crossing:markings=*

### ISSUE THREAD

**Issue by kaneap** [openstreetmap/id-tagging-schema#589]
### OSM Tag(s)

crossing:markings=*

### How would you like this tag to see supported?

As a Field

### Label

Crosswalk markings

### Terms

Crossing markings

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Key:crossing:markings

### Status of the Tag

Approved

### Usage of the tag

1,472

### Further Information

This tag was recently approved.

Pehaps display the implied values in gray (`crossing=marked`,`crossing=traffic_signals` (and maybe `crossing=uncontrolled`) implies `crossing:markings=yes`)

Also see #408 for the discussion on whether iD should be tagging `crossing=uncontrolled` instead of `crossing=marked`, and #507 for the tagging of signalized but unmarked crossings (which would be resolved by adding this field).

Thanks!

**Comment by 1ec5** [comment]
> #507 for the tagging of signalized but unmarked crossings (which would be resolved by adding this field).

Yes and no, a `crossing:markings` field would make it _possible_ to indicate a signalized but unmarked crossing, but perhaps not in the most natural manner. The issue specifically requested a field to indicate signalization, which I think would continue to be useful regardless. The current plan is to more formally propose the already common `crossing:signals` key to further deconflict the `crossings` key. As with the `crossing:markings` proposal, there’s already some talk about being able to elaborate beyond a Boolean value. The Crossing With Pedestrian Signals preset would probably need to be renamed or removed at that point, because a crossing controlled by the main traffic signals, without a dedicated pedestrian signal face, could not be described as having “pedestrian signals”, even if `crossing=traffic_signals` remains literally accurate.
