### ISSUE TITLE
Add access field to Park preset

### ISSUE THREAD

**Issue by arch0345** [openstreetmap/id-tagging-schema#631]
A significant number of parks (~10K/1%) of parks also have an `access=*` tag [according to Taginfo](https://taginfo.openstreetmap.org/tags/leisure=park#combinations)

The same can be said for [Nature Reserves](https://taginfo.openstreetmap.org/tags/leisure=nature_reserve#combinations)

**Comment by 1ec5** [comment]
The Sports Center / Complex and Sports Club presets should probably have this field too. There are a lot of private tennis and swimming clubs and that sort of thing.

**Comment by tyrasd** [comment]
I've added the `access_simple` field "only" as an optional field, because there is a strong implication of a "default access value" (i.e. for parks adding an access tag is only required in the exceptional cases when they are not public, and sports centers/clubs can similarly assumed to be for customers/members only): In these cases it wouldn't add too much information if we asked mappers to fill in this field all the time.

For nature reserves, it's unfortunately a bit unclear what "access" specifically means for such map features (the [wiki](https://wiki.openstreetmap.org/wiki/Tag%3Aleisure%3Dnature_reserve) doesn't explicitly mention the usage). If it's about accessing any part of the respective areas, this can quickly lead to ambiguous situations like [here](https://www.openstreetmap.org/relation/8317126) or [here](https://www.openstreetmap.org/relation/2123459), where I would strongly assume that accessing the main roads, paths and railways through the nature reserves is allowed, despite the `access=private` on the areas. If `access` in this case should only "affect" the areas outside of the road/path network, we'd need a more specific field (label) IMO. I have still included the tag as an optional field, to at least show the currently mapped information.
