### ISSUE TITLE
Duplicated items in Transifex

### ISSUE THREAD

**Issue by Dimitar5555** [openstreetmap/id-tagging-schema#686]
There are quite a few duplicated items in Transifex. Is it possible to merge them?

![image](https://user-images.githubusercontent.com/19364673/206909246-2a637a1f-e012-473b-b4ba-9d1d1845e73d.png)
![image](https://user-images.githubusercontent.com/19364673/206909247-1151935c-4fdd-47da-a2c0-dbeb2c9c8799.png)
![image](https://user-images.githubusercontent.com/19364673/206909721-50f19617-e715-46da-8728-f748d0bbaa1b.png)

**Comment by tyrasd** [comment]
These duplicates used to be necessary in situations like where a field exists in two slightly different variants (e.g. the field for leaf type for forests and the leaf type for individual trees (which doesn't have the option to select `mixed`, but is otherwise equal to the other field). Now, after [v5](https://github.com/ideditor/schema-builder/blob/main/CHANGELOG.md#500) of the schema is out, it is possible to cross-reference strings between fields, making such duplicates (mostly) unnecessary. So to answer your question: yes, it is possible to get rid of these duplicates. I have however not yet refactored the whole repository. :blush:
