### ISSUE TITLE
"terms" should consistently be array, not "," delimited string

### ISSUE THREAD

**Issue by bryceco** [openstreetmap/id-tagging-schema#757]
Currently "terms" is sometimes a string with "," delimiters, and other times it's an array of strings. It should be consistently an array.

Similarly "aliases" should be an array rather than a "\n" delimited array.

**Comment by tyrasd** [comment]
you mean the difference between how the individual presets are defined here ([example](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/attraction/roller_coaster.json)) and the compiled output in the `dist` folder?

**Comment by bryceco** [comment]
I see them in the translation files in dist, like this:
"terms": "jardín botánico,jardin botanico,colección de plantas,plantas raras"

Different translators use different string delimiters, rather than the array notation. 

https://github.com/openstreetmap/id-tagging-schema/blob/09b0fd9ae7fc24c2f16423c39bcd535a78e884fd/dist/translations/es.json#L6441

**Comment by tyrasd** [comment]
Yes. I assume the `terms` were implemented like this because it is not really possible to otherwise offer an arbitrary number of translations per language (e.g. you could have 3 terms in English and only 1 in Japanese) and it was easier to just keep the format the same in the `dist` output. I would agree that splitting them in the output would make more sense from a data consumer point of view, and there is nothing really preventing us from doing it except backwards compatibility. To some extent this also applies to `aliases` with the difference that when these were introduced, transifex allowed newlines in translations, so this delimiter was chosen for ease of translating. Providing these also as post-processed arrays would still be beneficial, though.

Only thing is: to make such a change, a new major version of the schema would be required. Would you be so kind to open a new [issue in the schema-builder](https://github.com/ideditor/schema-builder/issues) repository for this?

**Comment by bryceco** [comment]
Oh I see, that makes sense. I’ll open an issue for it at schema-builder.

**Comment by bryceco** [comment]
https://github.com/ideditor/schema-builder/issues/84
