### ISSUE TITLE
What is preferred? Single issue with list of related issues or multiple issues?

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#779]
I opened

> "psychiatrist" is not finding anything

at https://github.com/openstreetmap/id-tagging-schema/issues/778

Now with extra testing I discovered very similar ones: 

- psychology seems likewise missing (and psychologist) - but see https://wiki.openstreetmap.org/wiki/Talk:Key:healthcare:speciality#psychologist
- and dialysis (see https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Ddialysis )
- nurse ( https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dnurse )
- OBGYN, ob/gyn should find gynecologist (which may be better named "obstetrician/gynecologist") - see https://osmus.slack.com/archives/C01BU04GW7L/p1675881005275539
- "eye doctor" and "eye doctors" should find ophthalmologists and optometrists, I think
- https://github.com/Helium314/SCEE/issues/408#issuecomment-1418611158 mentions dermatovenereology (no yet verified by me, linking so future me will remember it)

should I create separate issues for them?

Note to self: after any part of that issue or #778 is processed continue https://github.com/matkoniecz/Zazolc/commit/934d985d81ffbb7295c318b5958d214212485304

**Comment by tyrasd** [comment]
I'd say that a single issue for a bunch of closely related topics is fine in order to save you some work and not spam the issue inbox full. It also usually makes reviewing a bit more streamlined because typically background research tasks (e.g. looking up the OSM wiki, taginfo, ohsome stats, etc.) can be done in a single go for multiple related tags.

I'd however open a separate issue for different "tasks/problems", e.g. one issue for missing specializations of doctors, one issue for missing search terms, one issue for missing fields, etc.

That said, if you would however prefer to open individual issues for the various bullet points above, that's also fine for me.

**Comment by matkoniecz** [comment]
thanks! So this is answered and I will open issues, maybe grouping multiple similar for what I listed here
