### ISSUE TITLE
Additional synonym and maybe a better name for gynecologist

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/id-tagging-schema#789]
1) OBGYN, ob/gyn should find gynecologist

2) maybe "obstetrician/gynecologist" would be a better name - see https://osmus.slack.com/archives/C01BU04GW7L/p1675881005275539

note that obstetric part is already in specialty:

![screen03](https://user-images.githubusercontent.com/899988/218794628-2cd78b9e-df2a-46a2-8491-bf4fe4fef2cf.png)

**Comment by predatorprasad** [comment]
ig **neonatologists and chiropodist.** should also be added

**Comment by predatorprasad** [comment]
if that need to be done. pls tell me where to add that

**Comment by 1ec5** [comment]
The preset’s name is defined here:

https://github.com/openstreetmap/id-tagging-schema/blob/d40b047db07d8f702cc27872c514bd5f62f655a4/data/presets/amenity/doctors/gynaecology.json#L31

After changing it, you’d need to run `npm run build` to update the localizable string table.

Since the default locale is American English, “Obstetrician/Gynecologist” should be the preset’s name, with the other words being aliases (“OB/GYN” is especially common in this dialect). This is based on what [the wiki currently says](https://wiki.openstreetmap.org/wiki/Special:PermanentLink/2467224) about `healthcare:speciality=gynaecology` covering both fields.

**Comment by predatorprasad** [comment]
can we add ```neonatologists and chiropodist.``` to the terms ?

**Comment by 1ec5** [comment]
There’s a separate `healthcare:speciality=neonatology` tag for neonatologists and a separate `healthcare:speciality=podiatry` tag for chiropodiatrists. They already have entries in the Speciality field, but not their own presets yet. It would be misleading to add them as a synonym for this unrelated tag without creating a preset for those tags. Please open a separate issue about them.

https://github.com/openstreetmap/id-tagging-schema/blob/7a9a9d5e391a2f08b1a74588eeb0e6edd56eec31/data/fields/healthcare/speciality.json#L51 https://github.com/openstreetmap/id-tagging-schema/blob/7a9a9d5e391a2f08b1a74588eeb0e6edd56eec31/data/fields/healthcare/speciality.json#L70
