### ISSUE TITLE
Add `natural=peninsula` preset

### ISSUE THREAD

**Issue by quincylvania** [openstreetmap/id-tagging-schema#798]
### OSM Tag(s)

natural=peninsula

### How would you like this tag to see supported?

As a Preset

### Label

Peninsula

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:natural=peninsula

### Status of the Tag

Approved

### Usage of the tag

1600

### Further Information

While there are relatively few uses, the tag is used for some large and important features (e.g. the [Arabian Peninsula](https://www.openstreetmap.org/relation/5631846)).

**Comment by matkoniecz** [comment]
Note the already controversial/problematic handling of bays and their name tagging - especially enormous ones.

**Comment by quincylvania** [comment]
@matkoniecz Are you saying we shouldn't add a preset for this? iD already has presets for bays, capes, islands… lots of similar large features.

**Comment by matkoniecz** [comment]
> Are you saying we shouldn't add a preset for this?

Not entirely sure. If I would be then I would suggest either way.

Just mentioning that it is one of controversial tagging topics.

**Comment by tyrasd** [comment]
Thanks for pointing that out @matkoniecz .

>  similar large features

Another example for similarly large and fuzzy objects might be mountain ranges (e.g. https://www.openstreetmap.org/relation/2698607), which iD still has no dedicated preset for.

>  shouldn't add a preset for this

iD should have presets also for this kind of objects. The main question would be whether we want to make it searchable or hidden. But whatever we decide, we should consistently use the same for all "similar" presets. IMHO, it's not a big concern that users of iD (& co) would use this preset to create "enormous" objects which might be considered problematic because of their size.

**Comment by 1ec5** [comment]
If anyone manages to create one of the controversial monstrosities using iD, preset or no, they should win a prize.
