### ISSUE TITLE
add scheme to replace parking:lane:_side_=parallel/diagonal/perpendicular

### ISSUE THREAD

**Issue by tiptoptom** [openstreetmap/id-tagging-schema#879]
### Deprecated OSM Tag(s)

parking:lane:_side_=parallel/diagonal/perpendicular

### Replacement OSM Tag(s)

parking:_side_=lane
parking:_side_:orientation=parallel/diagonal/perpendicular

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Street_parking
old scheme: https://wiki.openstreetmap.org/wiki/Key:parking:lane

**Comment by tordans** [comment]
If this is something that would be merged we can add a few others as well. 

In the meantime there is https://github.com/osmberlin/osm-tag-updater and the Zlant editor has a updater integration (well hidden behind the 🔄 icon).

**Comment by tyrasd** [comment]
The implementation of tag deprecation rules here does not scale up super well if there are many versions of a tag to be considered… I'd say that adding these 9 cases would be fine, but (much) more than that would be a stretch.

@tordans Do you think you could provide the "business logic" part of the @osmberlin/osm-tag-updater as an npm module? Because, then I could quite easily build that completely into iD directly as a dedicated validation module.

**Comment by tiptoptom** [comment]
So I will now make a PR for the mentioned 9 cases?

**Comment by tordans** [comment]
> But, from a technical standpoint, I have to note that the implementation of tag deprecation rules here does not scale up well if there are many versions of a tag to be considered… I'd say that adding these 9 cases would be still fine, but (much) more than that would be a stretch.

The proposal lists some data at https://wiki.openstreetmap.org/wiki/Proposal:Street_parking_revision#Numbers_of_usage_of_the_current_schema

> Currently (as of the end of October 2022), about 260.000 road segments in OSM have "primary" parking lane tagging ([parking:lane:both](https://wiki.openstreetmap.org/wiki/Key:parking:lane:both)=*, [parking:lane:left](https://wiki.openstreetmap.org/wiki/Key:parking:lane:left)=* or [parking:lane:right](https://wiki.openstreetmap.org/wiki/Key:parking:lane:right)=*), (…)

All other old tags are tags are well below the 50k mark, so I think we should ignore those for deprecation rules.

Following this logic, we could add a deprecation rule for those cases:

Source: https://osmberlin.github.io/osm-tag-updater/#/list

<table class="mt-10 min-w-full"><thead class="border-b-2 border-violet-300"><tr><th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 md:pl-0">Old tag</th><th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">New tag (maybe missing fields)</th><th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Compare type</th><th scope="col" class="py-3.5 px-3 text-left text-sm font-semibold text-gray-900">Optional message</th></tr></thead><tbody class="divide-y divide-violet-200"><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=yes</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>parking:{SIDE}=yes</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=separate</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>parking:{SIDE}=separate</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=parallel</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>parking:{SIDE}:orientation=parallel</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=diagonal</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>parking:{SIDE}:orientation=diagonal</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=perpendicular</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>parking:{SIDE}:orientation=perpendicular</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=marked</code> ==> Not this one, too complex</td><td class="py-4 px-3 text-sm text-gray-500"><code>[
  "parking:{SIDE}:markings=yes",
  "fixme=Please provide the orientation of parked cars with parking:{SIDE}:orientation=parallel|diagonal|perpendicular"
]</code><code class="break-words">{
  "key": "parking:{SIDE}:orientation",
  "values": [
    "parallel",
    "diagonal",
    "perpendicular"
  ],
  "msg": "Please provide the orientation of parked cars. This information was not recorded previously, which is one of the benefits of the new schema."
}</code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=no</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>parking:{SIDE}=no</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=no_parking</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>[
  "parking:{SIDE}=no",
  "parking:{SIDE}:restriction=no_parking"
]</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=no_standing</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>[
  "parking:{SIDE}=no",
  "parking:{SIDE}:restriction=no_standing"
]</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=no_stopping</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>[
  "parking:{SIDE}=no",
  "parking:{SIDE}:restriction=no_stopping"
]</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr><tr><td class="py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 md:pl-0"><code>parking:lane:{SIDE}=fire_lane</code></td><td class="py-4 px-3 text-sm text-gray-500"><code>[
  "parking:{SIDE}=no",
  "parking:{SIDE}:restriction=no_stopping",
  "parking:{SIDE}:restriction:reason=fire_lane"
]</code><code class="break-words"></code></td><td class="py-4 px-3 text-sm text-gray-500">tag</td><td class="py-4 px-3 text-sm text-gray-500"></td></tr></tbody></table>

---

> @tordans Do you think you could provide the "business logic" part of the @osmberlin/osm-tag-updater as an npm module? Because, then I could quite easily build that completely into iD directly as a dedicated validation module.

In Theorie, yes. However, the app is not prepared for this (no NPM package) and some functions are not exposed properly, yet (the output is constructed during render ATM). It is not just the input-output-migration, but also warnings and notices that need to be added to the UI to make this a propper integration. The Zlant Editor Integration (https://github.com/zlant/parking-lanes) only does parts of what the  osmberlin/osm-tag-updater does, which is not ideal, since information gets lost… (but still, its great to have it in there, for advanced users…).

The main reason why we did not invest more time in this is, that we assume that those old should be migrated while also manually reviewing the data. And the parking lane layer for StreetComplete (which also understand the most important old tags) can be used to migrate the data quite well.

---

@tiptoptom: 

> So I will now make a PR for the mentioned 9 cases?

I general +1. But I think your migration is wrong. Using https://osmberlin.github.io/osm-tag-updater/#/manual I get
INPUT
> parking:lane:right=perpendicular
OUTPUG
> parking:right:orientation=perpendicular

But your PR suggest
> "parking:right": "perpendicular"

**Comment by tiptoptom** [comment]
@tordans of course you are right. I will add the "orientation" and also "parking:_side_=lane". And your tags maybe as well?
