### ISSUE TITLE
Add support for man_made=charge_point

### ISSUE THREAD

**Issue by jmarchon1** [openstreetmap/id-tagging-schema#896]
### OSM Tag(s)

man_made=charge_point

### How would you like this tag to see supported?

As a Preset

### Label

Electric Vehicle Charge Point

### Aliases

Charging Stall

### Terms

Charging Station

### Link to OSM Wiki page

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcharge_point

### Status of the Tag

Approved

### Usage of the tag

22

### Replaces other Tag?

No

### Regional Tag?

No

### Further Information

Just now a proposal based on a draft by me was approved, leading to the creation of this tag: [https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcharge_point](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dcharge_point)
It'd be nice if this was recognized by iD. Currently there are only 22 uses, but this expected to increase very rapidly, since the proposal has only just been approved.
The only fields that would go along with this tag would be `ref=*` and those to enter details on the sockets the charge points have.

**Comment by tyrasd** [comment]
:+1: 

> Usage of the tag
> 22

This number seems to be still quite low, but usage seems to be growing quite rapidly (55 as of right now).

> details on the sockets 

Currently, we don't have fields for these details (except for the `capacity` field), which would make this preset a little bit less useful.

> Aliases
> Charging Station

I would only include `Charging Station` as a _search term_, because it is already the name of the preset for `amentiy=charging_station`.
