### ISSUE TITLE
Question re opening_hours:covid19

### ISSUE THREAD

**Issue by govvin** [openstreetmap/id-tagging-schema#963]
Is the `opening_hours:covid19` key still useful, and should we still be asking that information in the presets?

**Comment by tordans** [comment]
I think we should remove the field from the presets, so it does not get any "promotion" anymore (not even as a "moreFields"-field).

But the real cleanup should happen with a MapRoulette Challenge. That could possibly be one of those "edit right inside MapRoulette" Challenges, so users can remove the tag with one click (if removing is the right thing to to in the given case). I suggest discussing this in the community forum because its a major update process that needs to be thoroughly thought through.

**Comment by govvin** [comment]
Another source is [Ça reste ouvert](https://blog.caresteouvert.fr/ca-reste-ouvert-ferme-ses-portes-le-30-septembre-2020/), which announced last May that they already disabled their app.

**Comment by govvin** [comment]
There is now a new thread in OSM talk mailing list,  proposing for a global clean-up,  and removal of this tag: https://lists.openstreetmap.org/pipermail/talk/2023-July/088353.html

When that moves forward, it wouldn't make any sense to include this in any preset.

**Comment by tyrasd** [comment]
The tag was removed from all presets now. :smiley: 

It could also be added to [`discarded.json`](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/discarded.json) (such that the tag is automatically removed whenever one edits an object with this tag), but the [wiki](https://wiki.openstreetmap.org/w/index.php?title=Key:opening_hours:covid19&oldid=2578388) seems to discourage that at the moment and would be made obsolete by an automated edit as [proposed](https://lists.openstreetmap.org/pipermail/talk/2023-July/088353.html) by @matkoniecz .
